import { environment } from "./environment";

export const ApiConfig = {
    USER_GET: environment.apiBaseUrl + '/employee/find/${id}',
    USER_ALL: environment.apiBaseUrl + '/employee/all',
    USER_ADD: environment.apiBaseUrl + '/employee/add',
    USER_DELETE: environment.apiBaseUrl + '/employee/delete/${id}',
    USER_UPDATE: environment.apiBaseUrl + '/employee/update',
    USER_UPDATE_LEAVE: environment.apiBaseUrl + '/employee/update-leave-days',
    LOGIN: environment.apiBaseUrl + '/auth/signin',
    REGISTER: environment.apiBaseUrl + '/auth/signup',
    ATTENDANCE_DOWNLOAD: environment.apiBaseUrl + '/attendance/download/excel',
    ATTENDANCE_QR_SET: environment.apiBaseUrl + '/attendance/qr/add',
    ATTENDANCE_QR_GET: environment.apiBaseUrl + '/attendance/qr/find',
    ATTENDANCE_QR_STOP: environment.apiBaseUrl + '/attendance/qr/stop',
    ATTENDANCE_CHECK_IN: environment.apiBaseUrl + '/attendance/clockIn',
    ATTENDANCE_CHECK_OUT: environment.apiBaseUrl + '/attendance/clockOut',
    ATTENDANCE_ALL: environment.apiBaseUrl + '/attendance/all',
    ATTENDANCE_GET_EMP: environment.apiBaseUrl + '/attendance/find-by-empid/${empId}',
    ATTENDANCE_DELETE: environment.apiBaseUrl + '/attendance/delete/${id}',
    LEAVE_ALL: environment.apiBaseUrl + '/leave/all',
    LEAVE_GET: environment.apiBaseUrl + '/leave/find/${id}',
    LEAVE_GET_BY_EMP: environment.apiBaseUrl + '/leave/find-by-emp/${empId}',
    LEAVE_ADD: environment.apiBaseUrl + '/leave/add',
    LEAVE_UPDATE: environment.apiBaseUrl + '/leave/update',
    LEAVE_DELETE: environment.apiBaseUrl + '/leave/delete/${id}',
    LEAVE_APPROVE: environment.apiBaseUrl + '/leave/approve-leave/${id}',
    LEAVE_DENY: environment.apiBaseUrl + '/leave/deny-leave',
    EVENT_ALL: environment.apiBaseUrl + '/event/all',
    EVENT_GET: environment.apiBaseUrl + '/event/find/${id}',
    EVENT_ADD: environment.apiBaseUrl + '/event/add',
    EVENT_UPDATE: environment.apiBaseUrl + '/event/update',
    EVENT_DELETE: environment.apiBaseUrl + '/event/delete/${id}',
    EVENT_GET_BY_DATE: environment.apiBaseUrl + '/event/find/event/dates',
};
