#MySQL Configuration
spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/testing
    #url: jdbc:mysql://localhost:3306/hrwdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true